### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by andricampagnaro** [andricampagnaro/documentacao_python3#1]
### Flask Bootstrap Docker

- [ ] GIT
  - [ ] Criar RoadMap do projeto
  - [ ] Criar projeto git
  - [ ] Iniciar uma VirtualEnv
  - [ ] Congelar pacotes

- [ ] Aplicativo em Flask
  - [ ] Criar o aplicativo básico
  - [ ] Chamar uma função externa
  - [ ] Utilizar um template em bootstrap
  - [ ] Capturar input de usuários

- [ ] Logs
  - [ ] Criar um programa de gravação de logs
  - [ ] Permitir que esses logs façam uma leitura contínua (observer)

- [ ] Docker e Kubernetes
  - [ ] Criar container com a aplicação
  - [ ] Criar container com o programa de gravação de logs
  - [ ] Fazer os containeres se conversarem
  - [ ] Automatizar esse ecossistema com o Kubernetes

- [ ] Outros pontos
  - [ ] Configurar VSCode
  - [ ] Cria testes unitários
  - [ ] Criar documentação
